# Generated by Django 5.2.6 on 2025-09-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, help_text='Optional short summary', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/images/')),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('business', 'Business'), ('marketing', 'Marketing'), ('consulting', 'Consulting'), ('cybersecurity', 'Cyber Security'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=50)),
                ('author', models.CharField(default='SystemCog Team', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
