# Generated by Django 5.2.6 on 2025-09-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_category_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comments_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='number_of_comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='number_of_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
