# Generated by Django 5.2.6 on 2025-09-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='slug',
        ),
    ]
