# Generated by Django 5.2.6 on 2025-09-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, help_text='Ideal size: 612px X 660px', null=True, upload_to='team/images/'),
        ),
    ]
