# Generated by Django 5.2.6 on 2025-09-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_teammember_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(help_text='Ideal size: 612px X 660px', upload_to='team/images/'),
        ),
    ]
