# Generated by Django 5.2.6 on 2025-09-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_teammember_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='author',
            field=models.CharField(default='SystemCog Team', max_length=100),
        ),
    ]
