# Generated by Django 5.2.6 on 2025-09-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_portfolio_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(help_text='Ideal size: 1712px X 840px', upload_to='portfolio/images/'),
        ),
    ]
