# Generated by Django 5.2.6 on 2025-09-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_alter_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='short_image',
            field=models.ImageField(blank=True, help_text='Ideal size: 832px X 840px', null=True, upload_to='portfolio/images/short/'),
        ),
    ]
