# Generated by Django 5.2.6 on 2025-09-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_portfolio_short_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='short_image',
            field=models.ImageField(help_text='Ideal size: 832px X 840px', upload_to='portfolio/images/short/'),
        ),
    ]
