# Generated by Django 5.2.6 on 2025-09-29 13:35

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_alter_portfolio_short_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, help_text='Domain must be systemcog.cc', max_length=254, null=True, validators=[portfolio.models.validate_systemcog_email]),
        ),
    ]
