# Generated by Django 5.2.6 on 2025-09-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_alter_teammember_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='portfolio.category'),
        ),
    ]
