# Generated by Django 5.2.6 on 2025-09-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_portfolio_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_image',
            field=models.ImageField(default='portfolio/images/p5_9on5uil.png', help_text='Ideal size: 832px X 680px', upload_to='blog/images/short/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, help_text='Ideal size: 1712px X 1080px', null=True, upload_to='blog/images/'),
        ),
    ]
