# Generated by Django 5.2.6 on 2025-09-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_blog_short_image_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='portfolio.tag'),
        ),
        migrations.DeleteModel(
            name='BlogTag',
        ),
    ]
