# Generated by Django 5.2.6 on 2025-09-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_blog_tags_delete_blogtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='quote',
            field=models.CharField(blank=True, help_text='Optional quote to highlight', max_length=255, null=True),
        ),
    ]
